bcdapp/urls.py
from django.conf.urls import url 
from .views import *


urlpatterns = [

    url(r'^school-admin/logout/$', AdminLogout.as_view(),
        name='adminlogout'),
    url(r'^school-admin/login/$', AdminLogin.as_view(),
        name='adminlogin'),




    url(r'^school-admin/$', AdminHomeView.as_view(), name='adminhome'),
    url(r'^school-admin/school/create/$',
        AdminOrganizationCreateView.as_view(), name='adminorganizationcreate'),
    url(r'^school-admin/school/(?P<pk>\d+)/update/$',
        AdminOrganizationUpdateView.as_view(), name='adminorganizationupdate'),

    url(r'^school-admin/blogs/$',
        AdminBlogListView.as_view(), name='adminbloglist'),
    url(r'^school-admin/blogs/create/$',
        AdminBlogCreateView.as_view(), name='adminblogcreate'),
    url(r'^school-admin/blogs/(?P<pk>\d+)/update/$',
        AdminBlogUpdateView.as_view(), name='adminblogupdate'),
    url(r'^school-admin/blogs/(?P<pk>\d+)/delete/$',
        AdminBlogDeleteView.as_view(), name='adminblogdelete'),

    url(r'^school-admin/events/$',
        AdminEventListView.as_view(), name='admineventlist'),
    url(r'^school-admin/events/create/$',
        AdminEventCreateView.as_view(), name='admineventcreate'),
    url(r'^school-admin/events/(?P<pk>\d+)/update/$',
        AdminEventUpdateView.as_view(), name='admineventupdate'),
    url(r'^school-admin/events/(?P<pk>\d+)/delete/$',
        AdminEventDeleteView.as_view(), name='admineventdelete'),

    url(r'^school-admin/gallery/$',
        AdminGalleryListView.as_view(), name='admingallerylist'),
    url(r'^school-admin/gallery/create/$',
        AdminGalleryCreateView.as_view(), name='admingallerycreate'),
    url(r'^school-admin/gallery/(?P<pk>\d+)/update/$',
        AdminGalleryUpdateView.as_view(), name='admingalleryupdate'),
    url(r'^school-admin/gallery/(?P<pk>\d+)/delete/$',
        AdminGalleryDeleteView.as_view(), name='admingallerydelete'),

    url(r'^school-admin/notices/$',
        AdminNoticeListView.as_view(), name='adminnoticelist'),
    url(r'^school-admin/notices/create/$',
        AdminNoticeCreateView.as_view(), name='adminnoticecreate'),
    url(r'^school-admin/notices/(?P<pk>\d+)/update/$',
        AdminNoticeUpdateView.as_view(), name='adminnoticeupdate'),
    url(r'^school-admin/notices/(?P<pk>\d+)/delete/$',
        AdminNoticeDeleteView.as_view(), name='adminnoticedelete'),

    url(r'^school-admin/staffs/$',
        AdminStaffListView.as_view(), name='adminstafflist'),
    url(r'^school-admin/staffs/create/$',
        AdminStaffCreateView.as_view(), name='adminstaffcreate'),
    url(r'^school-admin/staffs/(?P<pk>\d+)/update/$',
        AdminStaffUpdateView.as_view(), name='adminstaffupdate'),
    url(r'^school-admin/staffs/(?P<pk>\d+)/delete/$',
        AdminStaffDeleteView.as_view(), name='adminstaffdelete'),

    url(r'^school-admin/testimonials/$',
        AdminTestimonialListView.as_view(), name='admintestimoniallist'),
    url(r'^school-admin/testimonials/create/$',
        AdminTestimonialCreateView.as_view(), name='admintestimonialcreate'),
    url(r'^school-admin/testimonials/(?P<pk>\d+)/update/$',
        AdminTestimonialUpdateView.as_view(), name='admintestimonialupdate'),
    url(r'^school-admin/testimonials/(?P<pk>\d+)/delete/$',
        AdminTestimonialDeleteView.as_view(), name='admintestimonialdelete'),



    url(r'^school-admin/features/$',
        AdminFeaturesListView.as_view(), name='adminfeatureslist'),
    url(r'^school-admin/features/create/$',
        AdminFeaturesCreateView.as_view(), name='adminfeaturescreate'),
    url(r'^school-admin/features/(?P<pk>\d+)/update/$',
        AdminFeaturesUpdateView.as_view(), name='adminfeaturesupdate'),
    url(r'^school-admin/features/(?P<pk>\d+)/delete/$',
        AdminFeaturesDeleteView.as_view(), name='adminfeaturesdelete'),






    url(r'^school-admin/routine/$',
        AdminRoutineListView.as_view(), name='adminroutinelist'),
    url(r'^school-admin/routine/create/$',
        AdminRoutineCreateView.as_view(), name='adminroutinecreate'),
    url(r'^school-admin/routine/(?P<pk>\d+)/update/$',
        AdminRoutineUpdateView.as_view(), name='adminroutineupdate'),
    url(r'^school-admin/routine/(?P<pk>\d+)/delete/$',
        AdminRoutineDeleteView.as_view(), name='adminroutinedelete'),




    url(r'^school-admin/result/$',
        AdminResultListView.as_view(), name='adminresultlist'),
    url(r'^school-admin/result/create/$',
        AdminResultCreateView.as_view(), name='adminresultcreate'),
    url(r'^school-admin/result/(?P<pk>\d+)/update/$',
        AdminResultUpdateView.as_view(), name='adminresultupdate'),
    url(r'^school-admin/result/(?P<pk>\d+)/delete/$',
        AdminResultDeleteView.as_view(), name='adminresultdelete'),



    url(r'^school-admin/slider/$',
        AdminSliderListView.as_view(), name='adminsliderlist'),
    url(r'^school-admin/slider/create/$',
        AdminSliderCreateView.as_view(), name='adminslidercreate'),
    url(r'^school-admin/slider/(?P<pk>\d+)/update/$',
        AdminSliderUpdateView.as_view(), name='adminsliderupdate'),
    url(r'^school-admin/slider/(?P<pk>\d+)/delete/$',
        AdminSliderDeleteView.as_view(), name='adminsliderdelete'),    


# client side


	url(r'^$', ClientHomeView.as_view(), name='clienthome'),
	url(r'^about/$', ClientAboutView.as_view(), name='clientabout'),
	url(r'^gallery/$', ClientGalleryListView.as_view(), name='clientgallerylist'),
	url(r'^blog/$', ClientBlogListView.as_view(), name='clientbloglist'),
    url(r'^contact/$', ClientContactView.as_view(), name='clientcontact'),
    url(r'^admission/$', ClientAdmissionView.as_view(), name='clientadmission'),
    url(r'^feestructure/$', ClientFeatureslistView.as_view(), name='Clientfeatureslist'),
    url(r'^routine/$', ClientRoutineListView.as_view(), name='Clientroutinelist'),
    url(r'^result/$', ClientResultListView.as_view(), name='Clientresultlist'),
	


]

bcdproject/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('bcdapp.urls', namespace='bcdapp'))
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bcdapp/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import authenticate, login, logout
from django.core.urlresolvers import reverse_lazy
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.views.generic import *
from .models import *
from .forms import *


class AdminLogout(LoginRequiredMixin, View):
    def get(self, request):
        logout(request)
        return HttpResponseRedirect('/')


class AdminLogin(FormView):
    template_name = "bcdapp/admintemplates/adminlogin.html"
    form_class = AdminLoginForm
    success_url = '/school-admin/'

    def form_valid(self, form):
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user = authenticate(username=username, password=password)
        if user is not None and user.is_superuser:
            login(self.request, user)
        else:
            return render(self.request, self.template_name, {
                'form': form,
                'errors': 'Incorrect username or password'})
        return super().form_valid(form)





class AdminMixin(LoginRequiredMixin, object):
    login_url = '/school-admin/login/'

    def get_context_data(self, *args, **kwargs):
        context = super(AdminMixin, self).get_context_data(*args, **kwargs)
        context['organization'] = Organization.objects.get(id=1)
        return context


class DeleteMixin(LoginRequiredMixin, UpdateView):
    login_url = '/school-admin/login/'

    def form_valid(self, form):
        form.instance.deleted_at = timezone.now()
        form.save()
        return super().form_valid(form)


class AdminHomeView(AdminMixin, TemplateView):
    template_name = 'bcdapp/admintemplates/adminhome.html'

class AdminOrganizationCreateView(AdminMixin, CreateView):
    template_name = 'bcdapp/admintemplates/adminorganizationcreate.html'
    form_class = AdminOrganizationCreateForm
    success_url = reverse_lazy('bfsapp:adminhome')


class AdminOrganizationUpdateView(AdminMixin, UpdateView):
    template_name = 'bcdapp/admintemplates/adminorganizationcreate.html'
    model = Organization
    form_class = AdminOrganizationCreateForm
    success_url = reverse_lazy('bfsapp:adminhome')


class AdminBlogListView(AdminMixin, ListView):
    template_name = 'bcdapp/admintemplates/adminbloglist.html'
    queryset = Blog.objects.filter(deleted_at__isnull=True).order_by('-id')
    context_object_name = 'allblogs'


class AdminBlogCreateView(AdminMixin, CreateView):
    template_name = 'bcdapp/admintemplates/adminblogcreate.html'
    form_class = AdminBlogCreateForm
    success_url = reverse_lazy('bcdapp:adminbloglist')


class AdminBlogUpdateView(AdminMixin, UpdateView):
    template_name = 'bcdapp/admintemplates/adminblogcreate.html'
    model = Blog
    form_class = AdminBlogCreateForm
    success_url = reverse_lazy('bcdapp:adminbloglist')


class AdminBlogDeleteView(AdminMixin, DeleteMixin):
    template_name = 'bcdapp/admintemplates/adminblogdelete.html'
    model = Blog
    form_class = AdminBlogDeleteForm
    success_url = reverse_lazy('bcdapp:adminbloglist')


class AdminEventListView(AdminMixin, ListView):
    template_name = 'bcdapp/admintemplates/admineventlist.html'
    queryset = Event.objects.filter(deleted_at__isnull=True).order_by('-id')
    context_object_name = 'allevents'


class AdminEventCreateView(AdminMixin, CreateView):
    template_name = 'bcdapp/admintemplates/admineventcreate.html'
    form_class = AdminEventCreateForm
    success_url = reverse_lazy('bcdapp:admineventlist')


class AdminEventUpdateView(AdminMixin, UpdateView):
    template_name = 'bcdapp/admintemplates/admineventcreate.html'
    model = Event
    form_class = AdminEventCreateForm
    success_url = reverse_lazy('bcdapp:admineventlist')


class AdminEventDeleteView(AdminMixin, DeleteMixin):
    template_name = 'bcdapp/admintemplates/admineventdelete.html'
    model = Event
    form_class = AdminEventDeleteForm
    success_url = reverse_lazy('bcdapp:admineventlist')


class AdminGalleryListView(AdminMixin, ListView):
    template_name = 'bcdapp/admintemplates/admingallerylist.html'
    queryset = Gallery.objects.filter(deleted_at__isnull=True).order_by('-id')
    context_object_name = 'allgallery'


class AdminGalleryCreateView(AdminMixin, CreateView):
    template_name = 'bcdapp/admintemplates/admingallerycreate.html'
    form_class = AdminGalleryCreateForm
    success_url = reverse_lazy('bcdapp:admingallerylist')


class AdminGalleryUpdateView(AdminMixin, UpdateView):
    template_name = 'bcdapp/admintemplates/admingallerycreate.html'
    model = Gallery
    form_class = AdminGalleryCreateForm
    success_url = reverse_lazy('bcdapp:admingallerylist')


class AdminGalleryDeleteView(AdminMixin, DeleteMixin):
    template_name = 'bcdapp/admintemplates/admingallerydelete.html'
    model = Gallery
    form_class = AdminGalleryDeleteForm
    success_url = reverse_lazy('bcdapp:admingallerylist')


class AdminNoticeListView(AdminMixin, ListView):
    template_name = 'bcdapp/admintemplates/adminnoticelist.html'
    queryset = Notice.objects.filter(deleted_at__isnull=True).order_by('-id')
    context_object_name = 'allnotices'


class AdminNoticeCreateView(AdminMixin, CreateView):
    template_name = 'bcdapp/admintemplates/adminnoticecreate.html'
    form_class = AdminNoticeCreateForm
    success_url = reverse_lazy('bcdapp:adminnoticelist')


class AdminNoticeUpdateView(AdminMixin, UpdateView):
    template_name = 'bcdapp/admintemplates/adminnoticecreate.html'
    model = Notice
    form_class = AdminNoticeCreateForm
    success_url = reverse_lazy('bcdapp:adminnoticelist')


class AdminNoticeDeleteView(AdminMixin, DeleteMixin):
    template_name = 'bcdapp/admintemplates/adminnoticedelete.html'
    model = Notice
    form_class = AdminNoticeDeleteForm
    success_url = reverse_lazy('bcdapp:adminnoticelist')


class AdminStaffListView(AdminMixin, ListView):
    template_name = 'bcdapp/admintemplates/adminstafflist.html'
    queryset = Staff.objects.filter(deleted_at__isnull=True).order_by('-id')
    context_object_name = 'allstaffs'


class AdminStaffCreateView(AdminMixin, CreateView):
    template_name = 'bcdapp/admintemplates/adminstaffcreate.html'
    form_class = AdminStaffCreateForm
    success_url = reverse_lazy('bcdapp:adminstafflist')


class AdminStaffUpdateView(AdminMixin, UpdateView):
    template_name = 'bcdapp/admintemplates/adminstaffcreate.html'
    model = Staff
    form_class = AdminStaffCreateForm
    success_url = reverse_lazy('bcdapp:adminstafflist')


class AdminStaffDeleteView(AdminMixin, DeleteMixin):
    template_name = 'bcdapp/admintemplates/adminstaffdelete.html'
    model = Staff
    form_class = AdminStaffDeleteForm
    success_url = reverse_lazy('bcdapp:adminstafflist')


class AdminTestimonialListView(AdminMixin, ListView):
    template_name = 'bcdapp/admintemplates/admintestimoniallist.html'
    queryset = Testimonial.objects.filter(
        deleted_at__isnull=True).order_by('-id')
    context_object_name = 'alltestimonials'


class AdminTestimonialCreateView(AdminMixin, CreateView):
    template_name = 'bcdapp/admintemplates/admintestimonialcreate.html'
    form_class = AdminTestimonialCreateForm
    success_url = reverse_lazy('bcdapp:admintestimoniallist')


class AdminTestimonialUpdateView(AdminMixin, UpdateView):
    template_name = 'bcdapp/admintemplates/admintestimonialcreate.html'
    model = Testimonial
    form_class = AdminTestimonialCreateForm
    success_url = reverse_lazy('bcdapp:admintestimoniallist')


class AdminTestimonialDeleteView(AdminMixin, DeleteMixin):
    template_name = 'bcdapp/admintemplates/admintestimonialdelete.html'
    model = Testimonial
    form_class = AdminTestimonialDeleteForm
    success_url = reverse_lazy('bcdapp:admintestimoniallist')




class AdminFeaturesListView(AdminMixin, ListView):
    template_name = 'bcdapp/admintemplates/adminfeatureslist.html'
    queryset = Features.objects.filter(deleted_at__isnull=True).order_by('-id')
    context_object_name = 'allfeatures'


class AdminFeaturesCreateView(AdminMixin, CreateView):
    template_name = 'bcdapp/admintemplates/adminfeaturescreate.html'
    form_class = AdminFeaturesCreateForm
    success_url = reverse_lazy('bcdapp:adminfeatureslist')


class AdminFeaturesUpdateView(AdminMixin, UpdateView):
    template_name = 'bcdapp/admintemplates/adminfeaturesreate.html'
    model = Features
    form_class = AdminFeaturesCreateForm
    success_url = reverse_lazy('bcdapp:adminfeatureslist')


class AdminFeaturesDeleteView(AdminMixin, DeleteMixin):
    template_name = 'bcdapp/admintemplates/adminfeaturesdelete.html'
    model = Features
    form_class = AdminFeaturesDeleteForm
    success_url = reverse_lazy('bcdapp:adminfeatureslist')



class AdminRoutineListView(AdminMixin, ListView):
    template_name = 'bcdapp/admintemplates/adminroutinelist.html'
    queryset = Routine.objects.filter(deleted_at__isnull=True)
    context_object_name = 'allroutines'


class AdminRoutineCreateView(AdminMixin, CreateView):
    template_name = 'bcdapp/admintemplates/adminroutinecreate.html'
    form_class = AdminRoutineCreateForm
    success_url = reverse_lazy('bcdapp:adminroutinelist')


class AdminRoutineUpdateView(AdminMixin, UpdateView):
    template_name = 'bcdapp/admintemplates/adminroutinecreate.html'
    model = Routine
    form_class = AdminRoutineCreateForm
    success_url = reverse_lazy('bcdapp:adminroutinelist')


class AdminRoutineDeleteView(AdminMixin, DeleteMixin):
    template_name = 'bcdapp/admintemplates/adminroutinedelete.html'
    model = Routine
    form_class = AdminRoutineDeleteForm
    success_url = reverse_lazy('bcdapp:adminroutinelist')



class AdminResultListView(AdminMixin, ListView):
    template_name = 'bcdapp/admintemplates/adminresultlist.html'
    queryset = Result.objects.filter(deleted_at__isnull=True)
    context_object_name = 'allresults'

templates/bcdapp/clienttemplates/Clientresultlist.html
{% extends 'bcdapp/clienttemplates/base.html' %}
{% load static %}


{% block content %}




{% endblock content %}

templates/bcdapp/clienttemplates/Clientroutinelist.html
{% extends 'bcdapp/clienttemplates/base.html' %}
{% load static %}


{% block content %}




{% endblock content %}

templates/bcdapp/clienttemplates/base.html
{% load static %}

<!--
Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE html>
<html lang="zxx">

<head>
	<title>Best Study an Education Category Bootstrap Responsive Website Template | Home :: w3layouts</title>
	<!-- meta-tags -->
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="keywords" content="Soft Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, 
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
	<script>
		addEventListener("load", function () {
			setTimeout(hideURLbar, 0);
		}, false);

		function hideURLbar() {
			window.scrollTo(0, 1);
		}
	</script>
	<!-- //meta-tags -->
	<link href="{% static 'clientstatic/css/bootstrap.css' %}" rel="stylesheet" type="text/css" media="all" />
	<link href="{% static 'clientstatic/css/style.css' %}" rel="stylesheet" type="text/css" media="all" />
	<!-- font-awesome -->
	<link href="{% static 'clientstatic/css/font-awesome.css' %}" rel="stylesheet">
	<!-- fonts -->
	<link href="//fonts.googleapis.com/css?family=Raleway:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i"
	    rel="stylesheet">
	<link href="//fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i" rel="stylesheet">
</head>

<body>
	<!-- header -->
	<div class="header-top">
		<div class="container">
			<div class="bottom_header_left">
				<p>
					<span class="fa fa-map-marker" aria-hidden="true"></span>New Kampshire Mshinon, USA
				</p>
			</div>
			<div class="bottom_header_right">
				<div class="bottom-social-icons">
					<a class="facebook" href="#">
						<span class="fa fa-facebook"></span>
					</a>
					<a class="twitter" href="#">
						<span class="fa fa-twitter"></span>
					</a>
					<a class="pinterest" href="#">
						<span class="fa fa-pinterest-p"></span>
					</a>
					<a class="linkedin" href="#">
						<span class="fa fa-linkedin"></span>
					</a>
				</div>
				<div class="header-top-righ">
					<a href="login.html">
						<span class="fa fa-sign-out" aria-hidden="true"></span>Login</a>
				</div>
				<div class="clearfix"> </div>
			</div>
			<div class="clearfix"> </div>
		</div>
	</div>
	<div class="header">
		<div class="content white">
			<nav class="navbar navbar-default">
				<div class="container">
					<div class="navbar-header">
						<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
							<span class="sr-only">Toggle navigation</span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
						</button>
						<a class="navbar-brand" href="index.html">
							<h1>
								<span class="fa fa-leanpub" aria-hidden="true"></span>Best Study
								<label>Education & Courses</label>
							</h1>
						</a>
					</div>
					<!--/.navbar-header-->
					<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
						<nav class="link-effect-2" id="link-effect-2">
							<ul class="nav navbar-nav">
								<li class="active">
									<a href="{% url 'bcdapp:clienthome' %}" class="effect-3">Home</a>
								</li>
								<li>
									<a href="{% url 'bcdapp:clientabout' %}" class="effect-3">About Us</a>
								</li>
								<li>
									<a href="{% url 'bcdapp:clientbloglist' %}" class="effect-3">Blog</a>
								</li>
								<li>
									<a href="{% url 'bcdapp:Clientfeatureslist' %}" class="effect-3">Features</a>
								</li>
								<li class="dropdown">
									<a href="#" class="dropdown-toggle" data-toggle="dropdown">Pages
										<span class="caret"></span>
									</a>
									<ul class="dropdown-menu" role="menu">
										<li>
											<strong><a href="{% url 'bcdapp:Clientroutinelist' %}">Routine</a></strong>
										</li><hr>
										<li>
											<strong><a href="{% url 'bcdapp:Clientresultlist' %}">Result</a></strong>
										</li>
									</ul>
								</li>
								<li>
									<a href="{% url 'bcdapp:clientgallerylist' %}" class="effect-3">Gallery</a>
								</li>
								<li>
									<a href="{% url 'bcdapp:clientcontact' %}" class="effect-3">Contact Us</a>
								</li>
							</ul>
						</nav>
					</div>
					<!--/.navbar-collapse-->
					<!--/.navbar-->
				</div>
			</nav>
		</div>
	</div>

	{% block content %}





	{% endblock content %}




	<!-- footer -->
	<div class="mkl_footer">
		<div class="sub-footer">
			<div class="container">
				<div class="mkls_footer_grid">
					<div class="col-xs-4 mkls_footer_grid_left">
						<h4>Location:</h4>
						<p>educa mfdflimbg 1235, Ipswich,
							<br> Foxhall Road, USA</p>
					</div>
					<div class="col-xs-4 mkls_footer_grid_left">
						<h4>Mail Us:</h4>
						<p>
							<span>Phone : </span>001 234 5678</p>
						<p>
							<span>Email : </span>
							<a href="mailto:info@example.com">mail@example.com</a>
						</p>
					</div>
					<div class="col-xs-4 mkls_footer_grid_left">
						<h4>Opening Hours:</h4>
						<p>Working days : 8am-10pm</p>
						<p>Sunday
							<span>(closed)</span>
						</p>
					</div>
					<div class="clearfix"> </div>
				</div>
				<div class="botttom-nav-allah">
					<ul>
						<li>
							<a href="{% url 'bcdapp:clienthome' %}">Home</a>
						</li>
						<li>
							<a href="{% url 'bcdapp:clientabout' %}">About Us</a>
						</li>
						<li>
							<a href="{% url 'bcdapp:clientbloglist' %}">Blog</a>
						</li>
						<li>
							<a href="{% url 'bcdapp:Clientfeatureslist' %}">Features</a>
						</li>
						<li>
							<a href="{% url 'bcdapp:clientgallerylist' %}">Gallery</a>
						</li>
						<li>
							<a href="{% url 'bcdapp:clientcontact' %}">Contact</a>
						</li>

					</ul>
				</div>
				<!-- footer-button-info -->
				<div class="footer-middle-thanks">
					<h2>Thanks For watching</h2>
				</div>
				<!-- footer-button-info -->
			</div>
		</div>
		<div class="footer-copy-right">
			<div class="container">
				<div class="allah-copy">
					<p>© 2018 Best Study. All rights reserved | Design by
						<a href="http://w3layouts.com/">W3layouts</a>
					</p>
				</div>
				<div class="footercopy-social">
					<ul>
						<li>
							<a href="#">
								<span class="fa fa-facebook"></span>
							</a>
						</li>
						<li>
							<a href="#">
								<span class="fa fa-twitter"></span>
							</a>
						</li>
						<li>
							<a href="#">
								<span class="fa fa-rss"></span>
							</a>
						</li>
						<li>
							<a href="#">
								<span class="fa fa-vk"></span>
							</a>
						</li>
					</ul>
				</div>
				<div class="clearfix"></div>
			</div>
		</div>
	</div>
	<!--/footer -->

	<!-- js files -->
	<!-- js -->
	<script src="{% static 'clientstatic/js/jquery-2.1.4.min.js' %}"></script>
	<!-- bootstrap -->
	<script src="{% static 'clientstatic/js/bootstrap.js' %}"></script>
	<!-- stats numscroller-js-file -->
	<script src="{% static 'clientstatic/js/numscroller-1.0.js' %}"></script>
	<!-- //stats numscroller-js-file -->

	<!-- Flexslider-js for-testimonials -->
	<script>
		$(window).load(function () {
			$("#flexiselDemo1").flexisel({
				visibleItems: 1,
				animationSpeed: 1000,
				autoPlay: false,
				autoPlaySpeed: 3000,
				pauseOnHover: true,
				enableResponsiveBreakpoints: true,
				responsiveBreakpoints: {
					portrait: {
						changePoint: 480,
						visibleItems: 1
					},
					landscape: {
						changePoint: 640,
						visibleItems: 1
					},
					tablet: {
						changePoint: 768,
						visibleItems: 1
					}
				}
			});

		});
	</script>
	<script src="{% static 'clientstatic/js/jquery.flexisel.js' %}"></script>
	<!-- //Flexslider-js for-testimonials -->
	<!-- smooth scrolling -->
	<script src="{% static 'clientstatic/js/SmoothScroll.min.js' %}"></script>
	<script src="{% static 'clientstatic/js/move-top.js' %}"></script>
	<script src="{% static 'clientstatic/js/easing.js' %}"></script>
	<!-- here stars scrolling icon -->
	<script>
		$(document).ready(function () {
			/*
				var defaults = {
				containerID: 'toTop', // fading element id
				containerHoverID: 'toTopHover', // fading element hover id
				scrollSpeed: 1200,
				easingType: 'linear' 
				};
			*/

			$().UItoTop({
				easingType: 'easeOutQuart'
			});

		});
	</script>
	<!-- //here ends scrolling icon -->
	<!-- smooth scrolling -->
	<!-- //js-files -->

</body>

</html>