bcdapp/urls.py
from django.conf.urls import url 
from .views import *


urlpatterns = [

    url(r'^school-admin/logout/$', AdminLogout.as_view(),
        name='adminlogout'),
    url(r'^school-admin/login/$', AdminLogin.as_view(),
        name='adminlogin'),




    url(r'^school-admin/$', AdminHomeView.as_view(), name='adminhome'),
    url(r'^school-admin/school/create/$',
        AdminOrganizationCreateView.as_view(), name='adminorganizationcreate'),
    url(r'^school-admin/school/(?P<pk>\d+)/update/$',
        AdminOrganizationUpdateView.as_view(), name='adminorganizationupdate'),

    url(r'^school-admin/blogs/$',
        AdminBlogListView.as_view(), name='adminbloglist'),
    url(r'^school-admin/blogs/create/$',
        AdminBlogCreateView.as_view(), name='adminblogcreate'),
    url(r'^school-admin/blogs/(?P<pk>\d+)/update/$',
        AdminBlogUpdateView.as_view(), name='adminblogupdate'),
    url(r'^school-admin/blogs/(?P<pk>\d+)/delete/$',
        AdminBlogDeleteView.as_view(), name='adminblogdelete'),

    url(r'^school-admin/events/$',
        AdminEventListView.as_view(), name='admineventlist'),
    url(r'^school-admin/events/create/$',
        AdminEventCreateView.as_view(), name='admineventcreate'),
    url(r'^school-admin/events/(?P<pk>\d+)/update/$',
        AdminEventUpdateView.as_view(), name='admineventupdate'),
    url(r'^school-admin/events/(?P<pk>\d+)/delete/$',
        AdminEventDeleteView.as_view(), name='admineventdelete'),

    url(r'^school-admin/gallery/$',
        AdminGalleryListView.as_view(), name='admingallerylist'),
    url(r'^school-admin/gallery/create/$',
        AdminGalleryCreateView.as_view(), name='admingallerycreate'),
    url(r'^school-admin/gallery/(?P<pk>\d+)/update/$',
        AdminGalleryUpdateView.as_view(), name='admingalleryupdate'),
    url(r'^school-admin/gallery/(?P<pk>\d+)/delete/$',
        AdminGalleryDeleteView.as_view(), name='admingallerydelete'),

    url(r'^school-admin/notices/$',
        AdminNoticeListView.as_view(), name='adminnoticelist'),
    url(r'^school-admin/notices/create/$',
        AdminNoticeCreateView.as_view(), name='adminnoticecreate'),
    url(r'^school-admin/notices/(?P<pk>\d+)/update/$',
        AdminNoticeUpdateView.as_view(), name='adminnoticeupdate'),
    url(r'^school-admin/notices/(?P<pk>\d+)/delete/$',
        AdminNoticeDeleteView.as_view(), name='adminnoticedelete'),

    url(r'^school-admin/staffs/$',
        AdminStaffListView.as_view(), name='adminstafflist'),
    url(r'^school-admin/staffs/create/$',
        AdminStaffCreateView.as_view(), name='adminstaffcreate'),
    url(r'^school-admin/staffs/(?P<pk>\d+)/update/$',
        AdminStaffUpdateView.as_view(), name='adminstaffupdate'),
    url(r'^school-admin/staffs/(?P<pk>\d+)/delete/$',
        AdminStaffDeleteView.as_view(), name='adminstaffdelete'),

    url(r'^school-admin/testimonials/$',
        AdminTestimonialListView.as_view(), name='admintestimoniallist'),
    url(r'^school-admin/testimonials/create/$',
        AdminTestimonialCreateView.as_view(), name='admintestimonialcreate'),
    url(r'^school-admin/testimonials/(?P<pk>\d+)/update/$',
        AdminTestimonialUpdateView.as_view(), name='admintestimonialupdate'),
    url(r'^school-admin/testimonials/(?P<pk>\d+)/delete/$',
        AdminTestimonialDeleteView.as_view(), name='admintestimonialdelete'),



    url(r'^school-admin/features/$',
        AdminFeaturesListView.as_view(), name='adminfeatureslist'),
    url(r'^school-admin/features/create/$',
        AdminFeaturesCreateView.as_view(), name='adminfeaturescreate'),
    url(r'^school-admin/features/(?P<pk>\d+)/update/$',
        AdminFeaturesUpdateView.as_view(), name='adminfeaturesupdate'),
    url(r'^school-admin/features/(?P<pk>\d+)/delete/$',
        AdminFeaturesDeleteView.as_view(), name='adminfeaturesdelete'),






    url(r'^school-admin/routine/$',
        AdminRoutineListView.as_view(), name='adminroutinelist'),
    url(r'^school-admin/routine/create/$',
        AdminRoutineCreateView.as_view(), name='adminroutinecreate'),
    url(r'^school-admin/routine/(?P<pk>\d+)/update/$',
        AdminRoutineUpdateView.as_view(), name='adminroutineupdate'),
    url(r'^school-admin/routine/(?P<pk>\d+)/delete/$',
        AdminRoutineDeleteView.as_view(), name='adminroutinedelete'),




    url(r'^school-admin/result/$',
        AdminResultListView.as_view(), name='adminresultlist'),
    url(r'^school-admin/result/create/$',
        AdminResultCreateView.as_view(), name='adminresultcreate'),
    url(r'^school-admin/result/(?P<pk>\d+)/update/$',
        AdminResultUpdateView.as_view(), name='adminresultupdate'),
    url(r'^school-admin/result/(?P<pk>\d+)/delete/$',
        AdminResultDeleteView.as_view(), name='adminresultdelete'),



    url(r'^school-admin/slider/$',
        AdminSliderListView.as_view(), name='adminsliderlist'),
    url(r'^school-admin/slider/create/$',
        AdminSliderCreateView.as_view(), name='adminslidercreate'),
    url(r'^school-admin/slider/(?P<pk>\d+)/update/$',
        AdminSliderUpdateView.as_view(), name='adminsliderupdate'),
    url(r'^school-admin/slider/(?P<pk>\d+)/delete/$',
        AdminSliderDeleteView.as_view(), name='adminsliderdelete'),    


# client side


	url(r'^$', ClientHomeView.as_view(), name='clienthome'),
	url(r'^about/$', ClientAboutView.as_view(), name='clientabout'),
	url(r'^gallery/$', ClientGalleryListView.as_view(), name='clientgallerylist'),
	url(r'^blog/$', ClientBlogListView.as_view(), name='clientbloglist'),
    url(r'^contact/$', ClientContactView.as_view(), name='clientcontact'),
    url(r'^admission/$', ClientAdmissionView.as_view(), name='clientadmission'),
    url(r'^feestructure/$', ClientFeatureslistView.as_view(), name='Clientfeatureslist'),
    url(r'^routine/$', ClientRoutineListView.as_view(), name='Clientroutinelist'),
    url(r'^result/$', ClientResultListView.as_view(), name='Clientresultlist'),
	


]

bcdproject/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('bcdapp.urls', namespace='bcdapp'))
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bcdapp/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import authenticate, login, logout
from django.core.urlresolvers import reverse_lazy
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.views.generic import *
from .models import *
from .forms import *


class AdminLogout(LoginRequiredMixin, View):
    def get(self, request):
        logout(request)
        return HttpResponseRedirect('/')


class AdminLogin(FormView):
    template_name = "bcdapp/admintemplates/adminlogin.html"
    form_class = AdminLoginForm
    success_url = '/school-admin/'

    def form_valid(self, form):
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user = authenticate(username=username, password=password)
        if user is not None and user.is_superuser:
            login(self.request, user)
        else:
            return render(self.request, self.template_name, {
                'form': form,
                'errors': 'Incorrect username or password'})
        return super().form_valid(form)





class AdminMixin(LoginRequiredMixin, object):
    login_url = '/school-admin/login/'

    def get_context_data(self, *args, **kwargs):
        context = super(AdminMixin, self).get_context_data(*args, **kwargs)
        context['organization'] = Organization.objects.get(id=1)
        return context


class DeleteMixin(LoginRequiredMixin, UpdateView):
    login_url = '/school-admin/login/'

    def form_valid(self, form):
        form.instance.deleted_at = timezone.now()
        form.save()
        return super().form_valid(form)


class AdminHomeView(AdminMixin, TemplateView):
    template_name = 'bcdapp/admintemplates/adminhome.html'

class AdminOrganizationCreateView(AdminMixin, CreateView):
    template_name = 'bcdapp/admintemplates/adminorganizationcreate.html'
    form_class = AdminOrganizationCreateForm
    success_url = reverse_lazy('bfsapp:adminhome')


class AdminOrganizationUpdateView(AdminMixin, UpdateView):
    template_name = 'bcdapp/admintemplates/adminorganizationcreate.html'
    model = Organization
    form_class = AdminOrganizationCreateForm
    success_url = reverse_lazy('bfsapp:adminhome')


class AdminBlogListView(AdminMixin, ListView):
    template_name = 'bcdapp/admintemplates/adminbloglist.html'
    queryset = Blog.objects.filter(deleted_at__isnull=True).order_by('-id')
    context_object_name = 'allblogs'


class AdminBlogCreateView(AdminMixin, CreateView):
    template_name = 'bcdapp/admintemplates/adminblogcreate.html'
    form_class = AdminBlogCreateForm
    success_url = reverse_lazy('bcdapp:adminbloglist')


class AdminBlogUpdateView(AdminMixin, UpdateView):
    template_name = 'bcdapp/admintemplates/adminblogcreate.html'
    model = Blog
    form_class = AdminBlogCreateForm
    success_url = reverse_lazy('bcdapp:adminbloglist')


class AdminBlogDeleteView(AdminMixin, DeleteMixin):
    template_name = 'bcdapp/admintemplates/adminblogdelete.html'
    model = Blog
    form_class = AdminBlogDeleteForm
    success_url = reverse_lazy('bcdapp:adminbloglist')


class AdminEventListView(AdminMixin, ListView):
    template_name = 'bcdapp/admintemplates/admineventlist.html'
    queryset = Event.objects.filter(deleted_at__isnull=True).order_by('-id')
    context_object_name = 'allevents'


class AdminEventCreateView(AdminMixin, CreateView):
    template_name = 'bcdapp/admintemplates/admineventcreate.html'
    form_class = AdminEventCreateForm
    success_url = reverse_lazy('bcdapp:admineventlist')


class AdminEventUpdateView(AdminMixin, UpdateView):
    template_name = 'bcdapp/admintemplates/admineventcreate.html'
    model = Event
    form_class = AdminEventCreateForm
    success_url = reverse_lazy('bcdapp:admineventlist')


class AdminEventDeleteView(AdminMixin, DeleteMixin):
    template_name = 'bcdapp/admintemplates/admineventdelete.html'
    model = Event
    form_class = AdminEventDeleteForm
    success_url = reverse_lazy('bcdapp:admineventlist')


class AdminGalleryListView(AdminMixin, ListView):
    template_name = 'bcdapp/admintemplates/admingallerylist.html'
    queryset = Gallery.objects.filter(deleted_at__isnull=True).order_by('-id')
    context_object_name = 'allgallery'


class AdminGalleryCreateView(AdminMixin, CreateView):
    template_name = 'bcdapp/admintemplates/admingallerycreate.html'
    form_class = AdminGalleryCreateForm
    success_url = reverse_lazy('bcdapp:admingallerylist')


class AdminGalleryUpdateView(AdminMixin, UpdateView):
    template_name = 'bcdapp/admintemplates/admingallerycreate.html'
    model = Gallery
    form_class = AdminGalleryCreateForm
    success_url = reverse_lazy('bcdapp:admingallerylist')


class AdminGalleryDeleteView(AdminMixin, DeleteMixin):
    template_name = 'bcdapp/admintemplates/admingallerydelete.html'
    model = Gallery
    form_class = AdminGalleryDeleteForm
    success_url = reverse_lazy('bcdapp:admingallerylist')


class AdminNoticeListView(AdminMixin, ListView):
    template_name = 'bcdapp/admintemplates/adminnoticelist.html'
    queryset = Notice.objects.filter(deleted_at__isnull=True).order_by('-id')
    context_object_name = 'allnotices'


class AdminNoticeCreateView(AdminMixin, CreateView):
    template_name = 'bcdapp/admintemplates/adminnoticecreate.html'
    form_class = AdminNoticeCreateForm
    success_url = reverse_lazy('bcdapp:adminnoticelist')


class AdminNoticeUpdateView(AdminMixin, UpdateView):
    template_name = 'bcdapp/admintemplates/adminnoticecreate.html'
    model = Notice
    form_class = AdminNoticeCreateForm
    success_url = reverse_lazy('bcdapp:adminnoticelist')


class AdminNoticeDeleteView(AdminMixin, DeleteMixin):
    template_name = 'bcdapp/admintemplates/adminnoticedelete.html'
    model = Notice
    form_class = AdminNoticeDeleteForm
    success_url = reverse_lazy('bcdapp:adminnoticelist')


class AdminStaffListView(AdminMixin, ListView):
    template_name = 'bcdapp/admintemplates/adminstafflist.html'
    queryset = Staff.objects.filter(deleted_at__isnull=True).order_by('-id')
    context_object_name = 'allstaffs'


class AdminStaffCreateView(AdminMixin, CreateView):
    template_name = 'bcdapp/admintemplates/adminstaffcreate.html'
    form_class = AdminStaffCreateForm
    success_url = reverse_lazy('bcdapp:adminstafflist')


class AdminStaffUpdateView(AdminMixin, UpdateView):
    template_name = 'bcdapp/admintemplates/adminstaffcreate.html'
    model = Staff
    form_class = AdminStaffCreateForm
    success_url = reverse_lazy('bcdapp:adminstafflist')


class AdminStaffDeleteView(AdminMixin, DeleteMixin):
    template_name = 'bcdapp/admintemplates/adminstaffdelete.html'
    model = Staff
    form_class = AdminStaffDeleteForm
    success_url = reverse_lazy('bcdapp:adminstafflist')


class AdminTestimonialListView(AdminMixin, ListView):
    template_name = 'bcdapp/admintemplates/admintestimoniallist.html'
    queryset = Testimonial.objects.filter(
        deleted_at__isnull=True).order_by('-id')
    context_object_name = 'alltestimonials'


class AdminTestimonialCreateView(AdminMixin, CreateView):
    template_name = 'bcdapp/admintemplates/admintestimonialcreate.html'
    form_class = AdminTestimonialCreateForm
    success_url = reverse_lazy('bcdapp:admintestimoniallist')


class AdminTestimonialUpdateView(AdminMixin, UpdateView):
    template_name = 'bcdapp/admintemplates/admintestimonialcreate.html'
    model = Testimonial
    form_class = AdminTestimonialCreateForm
    success_url = reverse_lazy('bcdapp:admintestimoniallist')


class AdminTestimonialDeleteView(AdminMixin, DeleteMixin):
    template_name = 'bcdapp/admintemplates/admintestimonialdelete.html'
    model = Testimonial
    form_class = AdminTestimonialDeleteForm
    success_url = reverse_lazy('bcdapp:admintestimoniallist')




class AdminFeaturesListView(AdminMixin, ListView):
    template_name = 'bcdapp/admintemplates/adminfeatureslist.html'
    queryset = Features.objects.filter(deleted_at__isnull=True).order_by('-id')
    context_object_name = 'allfeatures'


class AdminFeaturesCreateView(AdminMixin, CreateView):
    template_name = 'bcdapp/admintemplates/adminfeaturescreate.html'
    form_class = AdminFeaturesCreateForm
    success_url = reverse_lazy('bcdapp:adminfeatureslist')


class AdminFeaturesUpdateView(AdminMixin, UpdateView):
    template_name = 'bcdapp/admintemplates/adminfeaturesreate.html'
    model = Features
    form_class = AdminFeaturesCreateForm
    success_url = reverse_lazy('bcdapp:adminfeatureslist')


class AdminFeaturesDeleteView(AdminMixin, DeleteMixin):
    template_name = 'bcdapp/admintemplates/adminfeaturesdelete.html'
    model = Features
    form_class = AdminFeaturesDeleteForm
    success_url = reverse_lazy('bcdapp:adminfeatureslist')



class AdminRoutineListView(AdminMixin, ListView):
    template_name = 'bcdapp/admintemplates/adminroutinelist.html'
    queryset = Routine.objects.filter(deleted_at__isnull=True)
    context_object_name = 'allroutines'


class AdminRoutineCreateView(AdminMixin, CreateView):
    template_name = 'bcdapp/admintemplates/adminroutinecreate.html'
    form_class = AdminRoutineCreateForm
    success_url = reverse_lazy('bcdapp:adminroutinelist')


class AdminRoutineUpdateView(AdminMixin, UpdateView):
    template_name = 'bcdapp/admintemplates/adminroutinecreate.html'
    model = Routine
    form_class = AdminRoutineCreateForm
    success_url = reverse_lazy('bcdapp:adminroutinelist')


class AdminRoutineDeleteView(AdminMixin, DeleteMixin):
    template_name = 'bcdapp/admintemplates/adminroutinedelete.html'
    model = Routine
    form_class = AdminRoutineDeleteForm
    success_url = reverse_lazy('bcdapp:adminroutinelist')



class AdminResultListView(AdminMixin, ListView):
    template_name = 'bcdapp/admintemplates/adminresultlist.html'
    queryset = Result.objects.filter(deleted_at__isnull=True)
    context_object_name = 'allresults'

templates/bcdapp/admintemplates/adminbloglist.html
{% extends 'bcdapp/admintemplates/base.html' %}
{% load static %}
{% block blogs %}active{% endblock blogs%}
{% block css %}
<link href="{% static 'adminstatic/plugins/jquery-datatable/skin/bootstrap/css/dataTables.bootstrap.css' %}" rel="stylesheet">
{% endblock css %}

{% block content %}
        <div class="container-fluid">
            <!-- Basic Examples -->
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <h2>
                                BLog list
                            </h2>
                            <h2 class="pull-right">
                               <a href="{% url 'bcdapp:adminblogcreate' %}">Add New</i></a>
                            </h2>
                        </div>
                        <div class="body">
                            <div class="table-responsive">
                                <table class="table table-bordered table-striped table-hover js-basic-example dataTable">
                                    <thead>
                                        <tr>
                                            <th>SN</th>
                                            <th>Title</th>
                                            <th>Created At</th>
                                            <th>Image</th>
                                            <th>Action</th>
                                        </tr>
                                    </thead>
                                    <tfoot>
                                        <tr>
                                            <th>SN</th>
                                            <th>Title</th>
                                            <th>Created At</th>
                                            <th>Image</th>
                                            <th>Action</th>
                                        </tr>
                                    </tfoot>
                                    <tbody>
                                    	{% for blog in allblogs %}
                                        <tr>
                                            <td>{{forloop.counter}}</td>
                                            <td>{{blog.title}}</td>
                                            <td>{{blog.created_at}}</td>
                                            <td><img src="{{blog.image.url}}" width="50"></td>
                                            <td>
                                            	<a href="{% url 'bcdapp:adminblogupdate' blog.id %}" class="btn btn-default"> Update</a>
                                            	<a href="{% url 'bcdapp:adminblogdelete' blog.id %}" class="btn btn-danger" data-toggle="modal" data-target="#schoolmodal"> Delete</a>
                                            </td>
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
</div>
{% endblock content %}

{% block javascript %}
<script src="{% static 'adminstatic/plugins/jquery-datatable/jquery.dataTables.js' %}"></script>
<script src="{% static 'adminstatic/plugins/jquery-datatable/skin/bootstrap/js/dataTables.bootstrap.js' %}"></script>
<script src="{% static 'adminstatic/plugins/jquery-datatable/extensions/export/dataTables.buttons.min.js' %}"></script>
<script src="{% static 'adminstatic/js/pages/tables/jquery-datatable.js' %}"></script>
{% endblock javascript %}

templates/bcdapp/admintemplates/adminfeatureslist.html
{% extends 'bcdapp/admintemplates/base.html' %}
{% load static %}
{% block features %}active{% endblock features %}
{% block css %}
<link href="{% static 'adminstatic/plugins/jquery-datatable/skin/bootstrap/css/dataTables.bootstrap.css' %}" rel="stylesheet">
{% endblock css %}

{% block content %}
        <div class="container-fluid">
            <!-- Basic Examples -->
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <h2>
                                Features list
                            </h2>
                            <h2 class="pull-right">
                               <a href="{% url 'bcdapp:adminfeaturescreate' %}">Add New</i></a>
                            </h2>
                        </div>
                        <div class="body">
                            <div class="table-responsive">
                                <table class="table table-bordered table-striped table-hover js-basic-example dataTable">
                                    <thead>
                                        <tr>
                                            <th>SN</th>
                                            <th>Title</th> 
                                            <th>Image</th>
                                            <th>content</th>
                                            <th>Action</th>
                                        </tr>
                                    </thead>
                                    <tfoot>
                                        <tr>
                                            <th>SN</th>
                                            <th>Title</th>
                                            <th>Image</th>
                                            <th>content</th>
                                            <th>Action</th>
                                        </tr>
                                    </tfoot>
                                    <tbody>
                                    	{% for feature in allfeatures %}
                                        <tr>
                                            <td>{{forloop.counter}}</td>
                                            <td>{{feature.title}}</td>
                                            <td><img src="{{feature.image.url}}" width="50"></td>
                                            <td>{{feature.content}}</td>
                                            <td>
                                            	<a href="{% url 'bcdapp:adminfeaturesupdate' feature.id %}" class="btn btn-default"> Update</a>
                                            	<a href="{% url 'bcdapp:adminfeaturesdelete' feature.id %}" class="btn btn-danger" data-toggle="modal" data-target="#schoolmodal"> Delete</a>
                                            </td>
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
</div>
{% endblock content %}

{% block javascript %}
<script src="{% static 'adminstatic/plugins/jquery-datatable/jquery.dataTables.js' %}"></script>
<script src="{% static 'adminstatic/plugins/jquery-datatable/skin/bootstrap/js/dataTables.bootstrap.js' %}"></script>
<script src="{% static 'adminstatic/plugins/jquery-datatable/extensions/export/dataTables.buttons.min.js' %}"></script>
<script src="{% static 'adminstatic/js/pages/tables/jquery-datatable.js' %}"></script>
{% endblock javascript %}

templates/bcdapp/admintemplates/admingallerylist.html
{% extends 'bcdapp/admintemplates/base.html' %}
{% load static %}
{% block gallery %}active{% endblock gallery %}
{% block css %}
<link href="{% static 'adminstatic/plugins/jquery-datatable/skin/bootstrap/css/dataTables.bootstrap.css' %}" rel="stylesheet">
{% endblock css %}

{% block content %}
        <div class="container-fluid">
            <!-- Basic Examples -->
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <h2>
                                Gallery list
                            </h2>
                            <h2 class="pull-right">
                               <a href="{% url 'bcdapp:admingallerycreate' %}">Add New</i></a>
                            </h2>
                        </div>
                        <div class="body">
                            <div class="table-responsive">
                                <table class="table table-bordered table-striped table-hover js-basic-example dataTable">
                                    <thead>
                                        <tr>
                                            <th>SN</th>
                                            <th>Caption</th>
                                            <th>Created At</th>
                                            <th>Image</th>
                                            <th>Action</th>
                                        </tr>
                                    </thead>
                                    <tfoot>
                                        <tr>
                                            <th>SN</th>
                                            <th>Caption</th>
                                            <th>Created At</th>
                                            <th>Image</th>
                                            <th>Action</th>
                                        </tr>
                                    </tfoot>
                                    <tbody>
                                    	{% for image in allgallery %}
                                        <tr>
                                            <td>{{forloop.counter}}</td>
                                            <td>{{image.caption|truncatechars:"20"}}</td>
                                            <td>{{image.created_at}}</td>
                                            <td><img src="{{image.image.url}}" width="50"></td>
                                            <td>
                                            	<a href="{% url 'bcdapp:admingalleryupdate' image.id %}" class="btn btn-default"> Update</a>
                                            	<a href="{% url 'bcdapp:admingallerydelete' image.id %}" class="btn btn-danger" data-toggle="modal" data-target="#schoolmodal"> Delete</a>
                                            </td>
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
</div>
{% endblock content %}

{% block javascript %}
<script src="{% static 'adminstatic/plugins/jquery-datatable/jquery.dataTables.js' %}"></script>
<script src="{% static 'adminstatic/plugins/jquery-datatable/skin/bootstrap/js/dataTables.bootstrap.js' %}"></script>
<script src="{% static 'adminstatic/plugins/jquery-datatable/extensions/export/dataTables.buttons.min.js' %}"></script>
<script src="{% static 'adminstatic/js/pages/tables/jquery-datatable.js' %}"></script>
{% endblock javascript %}

templates/bcdapp/admintemplates/adminnoticelist.html
{% extends 'bcdapp/admintemplates/base.html' %}
{% load static %}
{% block notices %}active{% endblock notices %}
{% block css %}
<link href="{% static 'adminstatic/plugins/jquery-datatable/skin/bootstrap/css/dataTables.bootstrap.css' %}" rel="stylesheet">
{% endblock css %}

{% block content %}
        <div class="container-fluid">
            <!-- Basic Examples -->
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <h2>
                                Notices list
                            </h2>
                            <h2 class="pull-right">
                               <a href="{% url 'bcdapp:adminnoticecreate' %}">Add New</i></a>
                            </h2>
                        </div>
                        <div class="body">
                            <div class="table-responsive">
                                <table class="table table-bordered table-striped table-hover js-basic-example dataTable">
                                    <thead>
                                        <tr>
                                            <th>SN</th>
                                            <th>Title</th>
                                            <th>Created At</th>
                                            <th>Image</th>
                                            <th>Action</th>
                                        </tr>
                                    </thead>
                                    <tfoot>
                                        <tr>
                                            <th>SN</th>
                                            <th>Title</th>
                                            <th>Created At</th>
                                            <th>Image</th>
                                            <th>Action</th>
                                        </tr>
                                    </tfoot>
                                    <tbody>
                                    	{% for notice in allnotices %}
                                        <tr>
                                            <td>{{forloop.counter}}</td>
                                            <td>{{notice.title|truncatechars:"20"}}</td>
                                            <td>{{notice.created_at}}</td>
                                            <td><img src="{{notice.image.url}}" width="50"></td>
                                            <td>
                                            	<a href="{% url 'bcdapp:adminnoticeupdate' notice.id %}" class="btn btn-default"> Update</a>
                                            	<a href="{% url 'bcdapp:adminnoticedelete' notice.id %}" class="btn btn-danger" data-toggle="modal" data-target="#schoolmodal"> Delete</a>
                                            </td>
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
</div>
{% endblock content %}

{% block javascript %}
<script src="{% static 'adminstatic/plugins/jquery-datatable/jquery.dataTables.js' %}"></script>
<script src="{% static 'adminstatic/plugins/jquery-datatable/skin/bootstrap/js/dataTables.bootstrap.js' %}"></script>
<script src="{% static 'adminstatic/plugins/jquery-datatable/extensions/export/dataTables.buttons.min.js' %}"></script>
<script src="{% static 'adminstatic/js/pages/tables/jquery-datatable.js' %}"></script>
{% endblock javascript %}